apiVersion: v1
kind: Service
metadata:
  name: web-svc-lb-coredns-udp
  namespace: kube-system
spec:
  loadBalancerIP: 10.111.253.227
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  ports:
  - name: port1
    protocol: UDP
    port: 53
    targetPort: 53
